const constants = {
  MIN_PAGE: 0,
  MAX_PAGE: 3,
  ONE_PAGE_NEWSPAPER: 24,
  ALL_PAGE_NEWSPAPER: 96,
  ROLLING_TIMING_SEC: 5,
  ROLLING_DIFF_SEC: 1,
  ROLLING_TRANSITION_DURATION_MS: 400,
  LIGHT_MODE: "light",
  DARK_MODE: "dark",
};

export { constants };
