export let pressObjArr = [
  { id: 1, name: "머니투데이", src: "./assets/images/img1.png", isSub: false },
  { id: 2, name: "경향신문", src: "./assets/images/img2.png", isSub: false },
  { id: 3, name: "뉴스타파", src: "./assets/images/img3.png", isSub: false },
  { id: 4, name: "오마이뉴스", src: "./assets/images/img4.png", isSub: false },
  { id: 5, name: "데일리안", src: "./assets/images/img5.png", isSub: false },
  { id: 6, name: "스포츠서울", src: "./assets/images/img6.png", isSub: false },
  { id: 7, name: "스포츠동아", src: "./assets/images/img7.png", isSub: false },
  {
    id: 8,
    name: "석간문화일보",
    src: "./assets/images/img8.png",
    isSub: false,
  },
  { id: 9, name: "KBS WORLD", src: "./assets/images/img9.png", isSub: false },
  {
    id: 10,
    name: "중앙데일리",
    src: "./assets/images/img10.png",
    isSub: false,
  },
  { id: 11, name: "인사이트", src: "./assets/images/img11.png", isSub: false },
  {
    id: 12,
    name: "법률방송뉴스",
    src: "./assets/images/img12.png",
    isSub: false,
  },
  { id: 13, name: "시사저널e", src: "./assets/images/img13.png", isSub: false },
  {
    id: 14,
    name: "조이뉴스24",
    src: "./assets/images/img14.png",
    isSub: false,
  },
  {
    id: 15,
    name: "헤럴드경제",
    src: "./assets/images/img15.png",
    isSub: false,
  },
  {
    id: 16,
    name: "에너지경제",
    src: "./assets/images/img16.png",
    isSub: false,
  },
  {
    id: 17,
    name: "비즈니스포스트",
    src: "./assets/images/img17.png",
    isSub: false,
  },
  {
    id: 18,
    name: "스코어데일리",
    src: "./assets/images/img18.png",
    isSub: false,
  },
  { id: 19, name: "KNN", src: "./assets/images/img19.png", isSub: false },
  {
    id: 20,
    name: "더코리아헤럴드",
    src: "./assets/images/img20.png",
    isSub: false,
  },
  { id: 21, name: "MBC", src: "./assets/images/img21.png", isSub: false },
  { id: 22, name: "뉴데일리", src: "./assets/images/img22.png", isSub: false },
  { id: 23, name: "국민일보", src: "./assets/images/img23.png", isSub: false },
  {
    id: 24,
    name: "일간스포츠",
    src: "./assets/images/img24.png",
    isSub: false,
  },
  {
    id: 25,
    name: "ZD넷코리아",
    src: "./assets/images/img25.png",
    isSub: false,
  },
  {
    id: 26,
    name: "마이데일리",
    src: "./assets/images/img26.png",
    isSub: false,
  },
  { id: 27, name: "SBS", src: "./assets/images/img27.png", isSub: false },
  { id: 28, name: "서울경제", src: "./assets/images/img28.png", isSub: false },
  { id: 29, name: "매일경제", src: "./assets/images/img29.png", isSub: false },
  { id: 30, name: "MBN", src: "./assets/images/img30.png", isSub: false },
  { id: 31, name: "YTN", src: "./assets/images/img31.png", isSub: false },
  { id: 32, name: "시사위크", src: "./assets/images/img32.png", isSub: false },
  { id: 33, name: "세계일보", src: "./assets/images/img33.png", isSub: false },
  {
    id: 34,
    name: "디지털투데이",
    src: "./assets/images/img34.png",
    isSub: false,
  },
  {
    id: 35,
    name: "데이타뉴스",
    src: "./assets/images/img35.png",
    isSub: false,
  },
  {
    id: 36,
    name: "한국대학신문",
    src: "./assets/images/img36.png",
    isSub: false,
  },
  {
    id: 37,
    name: "서울파이낸스",
    src: "./assets/images/img37.png",
    isSub: false,
  },
  {
    id: 38,
    name: "엑스포츠뉴스",
    src: "./assets/images/img38.png",
    isSub: false,
  },
  { id: 39, name: "맥스무비", src: "./assets/images/img39.png", isSub: false },
  { id: 40, name: "OBS", src: "./assets/images/img40.png", isSub: false },
  {
    id: 41,
    name: "소년한국일보",
    src: "./assets/images/img41.png",
    isSub: false,
  },
  { id: 42, name: "한국일보", src: "./assets/images/img42.png", isSub: false },
  {
    id: 43,
    name: "스포탈코리아",
    src: "./assets/images/img43.png",
    isSub: false,
  },
  {
    id: 44,
    name: "아시아경제",
    src: "./assets/images/img44.png",
    isSub: false,
  },
  { id: 45, name: "프레시안", src: "./assets/images/img45.png", isSub: false },
  { id: 46, name: "노컷뉴스", src: "./assets/images/img46.png", isSub: false },
  { id: 47, name: "더중앙", src: "./assets/images/img47.png", isSub: false },
  { id: 48, name: "서울신문", src: "./assets/images/img48.png", isSub: false },
  {
    id: 49,
    name: "스포츠조선",
    src: "./assets/images/img49.png",
    isSub: false,
  },
  { id: 50, name: "전자신문", src: "./assets/images/img50.png", isSub: false },
  {
    id: 51,
    name: "한국경제TV",
    src: "./assets/images/img51.png",
    isSub: false,
  },
  { id: 52, name: "BLOTER", src: "./assets/images/img52.png", isSub: false },
  { id: 53, name: "KBS", src: "./assets/images/img53.png", isSub: false },
  { id: 54, name: "동아일보", src: "./assets/images/img54.png", isSub: false },
  { id: 55, name: "이데일리", src: "./assets/images/img55.png", isSub: false },
  { id: 56, name: "NEWSIS", src: "./assets/images/img56.png", isSub: false },
  { id: 57, name: "한국경제", src: "./assets/images/img57.png", isSub: false },
  { id: 58, name: "시사IN", src: "./assets/images/img58.png", isSub: false },
  { id: 59, name: "산", src: "./assets/images/img59.png", isSub: false },
  { id: 60, name: "독서신문", src: "./assets/images/img60.png", isSub: false },
  {
    id: 61,
    name: "ECONO TIMES",
    src: "./assets/images/img61.png",
    isSub: false,
  },
  { id: 62, name: "TJB", src: "./assets/images/img62.png", isSub: false },
  {
    id: 63,
    name: "시사오늘 시사온",
    src: "./assets/images/img63.png",
    isSub: false,
  },
  {
    id: 64,
    name: "데일리한국",
    src: "./assets/images/img64.png",
    isSub: false,
  },
  {
    id: 65,
    name: "뉴스토마토",
    src: "./assets/images/img65.png",
    isSub: false,
  },
  { id: 66, name: "조선일보", src: "./assets/images/img66.png", isSub: false },
  {
    id: 67,
    name: "에이블뉴스",
    src: "./assets/images/img67.png",
    isSub: false,
  },
  {
    id: 68,
    name: "YTN 사이언스",
    src: "./assets/images/img68.png",
    isSub: false,
  },
  { id: 69, name: "OSEN", src: "./assets/images/img69.png", isSub: false },
  {
    id: 70,
    name: "디지털타임스",
    src: "./assets/images/img70.png",
    isSub: false,
  },
  {
    id: 71,
    name: "미디어오늘",
    src: "./assets/images/img71.png",
    isSub: false,
  },
  { id: 72, name: "연합뉴스", src: "./assets/images/img72.png", isSub: false },
  { id: 73, name: "한겨레", src: "./assets/images/img73.png", isSub: false },
  { id: 74, name: "조선 BIZ", src: "./assets/images/img74.png", isSub: false },
  { id: 75, name: "JTBC", src: "./assets/images/img75.png", isSub: false },
  { id: 76, name: "METRO", src: "./assets/images/img76.png", isSub: false },
  {
    id: 77,
    name: "아이뉴스24",
    src: "./assets/images/img77.png",
    isSub: false,
  },
  { id: 78, name: "비즈한국", src: "./assets/images/img78.png", isSub: false },
  { id: 79, name: "주간경향", src: "./assets/images/img79.png", isSub: false },
  { id: 80, name: "FORBES", src: "./assets/images/img80.png", isSub: false },
  { id: 81, name: "TV REPORT", src: "./assets/images/img81.png", isSub: false },
  {
    id: 82,
    name: "티브이데일리",
    src: "./assets/images/img82.png",
    isSub: false,
  },
  { id: 83, name: "BBS", src: "./assets/images/img83.png", isSub: false },
  {
    id: 84,
    name: "디플로마티크",
    src: "./assets/images/img84.png",
    isSub: false,
  },
  { id: 85, name: "MK스포츠", src: "./assets/images/img85.png", isSub: false },
  { id: 86, name: "텐아시아", src: "./assets/images/img86.png", isSub: false },
  {
    id: 87,
    name: "정책브리핑",
    src: "./assets/images/img87.png",
    isSub: false,
  },
  {
    id: 88,
    name: "파이낸셜뉴스",
    src: "./assets/images/img88.png",
    isSub: false,
  },
  { id: 89, name: "씨네21", src: "./assets/images/img89.png", isSub: false },
  {
    id: 90,
    name: "뉴스포스트",
    src: "./assets/images/img90.png",
    isSub: false,
  },
  {
    id: 91,
    name: "정신의학신문",
    src: "./assets/images/img91.png",
    isSub: false,
  },
  {
    id: 92,
    name: "철강금속신문",
    src: "./assets/images/img92.png",
    isSub: false,
  },
  { id: 93, name: "IT조선", src: "./assets/images/img93.png", isSub: false },
  {
    id: 94,
    name: "여성경제신문",
    src: "./assets/images/img94.png",
    isSub: false,
  },
  { id: 95, name: "SBS Biz", src: "./assets/images/img95.png", isSub: false },
  {
    id: 96,
    name: "한국농어촌방송",
    src: "./assets/images/img96.png",
    isSub: false,
  },
];

export function shufflePress() {
  for (let i = pressObjArr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [pressObjArr[i], pressObjArr[j]] = [pressObjArr[j], pressObjArr[i]];
  }
}
