const COLOR = Object.freeze({
  GRAY_SCALE_WHITE_ALT: { hex: '#ffffff', opacity: 0.7 },
  GRAY_SCALE_WHITE: '#ffffff',
  GRAY_SCALE_50: '#f5f7f9',
  GRAY_SCALE_100: '#d2dae0',
  GRAY_SCALE_200: '#879298',
  GRAY_SCALE_300: '#6e8091',
  GRAY_SCALE_400: '#5f6e76',
  GRAY_SCALE_500: '#4b5966',
  GRAY_SCALE_BLACK: '#14212b',
  BLUE_100: '#7890e7',
  BLUE_500: '#4362D0',
});

const COLOR_LIGHT = Object.freeze({
  TEXT_STRONG: COLOR.GRAY_SCALE_BLACK,
  TEXT_BOLD: COLOR.GRAY_SCALE_500,
  TEXT_DEFAULT: COLOR.GRAY_SCALE_400,
  TEXT_WEAK: COLOR.GRAY_SCALE_200,
  TEXT_WHITE_DEFAULT: COLOR.GRAY_SCALE_WHITE,
  TEXT_WHITE_WEAK: COLOR.GRAY_SCALE_WHITE_ALT,
  TEXT_POINT: COLOR.BLUE_500,
  SURFACE_DEFAULT: COLOR.GRAY_SCALE_WHITE,
  SURFACE_ALT: COLOR.GRAY_SCALE_50,
  SURFACE_BRAND_DEFAULT: COLOR.BLUE_500,
  SURFACE_BRAND_ALT: COLOR.BLUE_100,
  BORDER_BOLD: GRAY_SCALE_300,
  BORDER_DEFAULT: GRAY_SCALE_100,
});

const COLOR_DARK = Object.freeze({
  TEXT_STRONG: COLOR.GRAY_SCALE_WHITE,
  TEXT_BOLD: COLOR.GRAY_SCALE_50,
  TEXT_DEFAULT: COLOR.GRAY_SCALE_100,
  TEXT_WEAK: COLOR.GRAY_SCALE_WHITE_ALT,
  TEXT_WHITE_DEFAULT: COLOR.GRAY_SCALE_WHITE,
  TEXT_WHITE_WEAK: COLOR.GRAY_SCALE_WHITE_ALT,
  TEXT_POINT: COLOR.BLUE_500,
  SURFACE_DEFAULT: COLOR.GRAY_SCALE_BLACK,
  SURFACE_ALT: COLOR.GRAY_SCALE_500,
  SURFACE_BRAND_DEFAULT: COLOR.BLUE_500,
  SURFACE_BRAND_ALT: COLOR.BLUE_100,
  BORDER_BOLD: GRAY_SCALE_WHITE_ALT,
  BORDER_DEFAULT: GRAY_SCALE_400,
});

export { COLOR_LIGHT, COLOR_DARK };
