export const HEADLINE_NUMBERS = 5;
export const HEADLINE_ROLLING_DELAY = 5000;
export const HEADLINE_ROLLING_DELAY_DIFF = 1000;

export const NEWS_PRESS_NUMBERS_PER_PAGE = 24;
export const PAGE_MIN_NUMBER = 1;
export const PAGE_MAX_NUMBER = 4;

export const CATEGORY_NUMBERS = 7;
export const ANIMATION_UPDATE_DELAY = 16.66;
export const PROGRESSBAR_DURATION = 20000;
export const PROGRESSBAR_UPDATE_DELTA = (100 / PROGRESSBAR_DURATION) * ANIMATION_UPDATE_DELAY;
